/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountButton: typeof import('./components/AccountButton.vue')['default']
    AddFriendButton: typeof import('./components/AddFriendButton.vue')['default']
    AddFriendDialog: typeof import('./components/AddFriendDialog.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    FriendsList: typeof import('./components/FriendsList.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./components/ThemeButton.vue')['default']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
  }
}
