/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountButton: (typeof import('./components/AccountButton.vue'))['default']
    AppBar: (typeof import('./components/AppBar.vue'))['default']
    NavigationDrawer: (typeof import('./components/NavigationDrawer.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    ThemeButton: (typeof import('./components/ThemeButton.vue'))['default']
    UserInfo: (typeof import('./components/UserInfo.vue'))['default']
  }
}
