/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountButton: typeof import('./components/AccountButton.vue')['default']
    AddFriendButton: typeof import('./components/AddFriendButton.vue')['default']
    AddFriendDialog: typeof import('./components/AddFriendDialog.vue')['default']
    AnnounceMessage: typeof import('./components/AnnounceMessage.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    ChangelogListItem: typeof import('./components/ChangelogListItem.vue')['default']
    ChatContainer: typeof import('./components/ChatContainer.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    DateBadge: typeof import('./components/DateBadge.vue')['default']
    FriendsList: typeof import('./components/FriendsList.vue')['default']
    FriendsListItem: typeof import('./components/FriendsListItem.vue')['default']
    FriendsListTitle: typeof import('./components/FriendsListTitle.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    MessagesContainer: typeof import('./components/MessagesContainer.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./components/ThemeButton.vue')['default']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
  }
}
